### ISSUE TITLE
Add dataset and repeat co-mut plot and gene pairs analysis

### ISSUE THREAD

**Issue by varsh1090** [zhoulab/sclc-scripts#3]
To add a new dataset with 44 samples to the previous analyses.

**Comment by varsh1090** [comment]
Updated file in - ZhouLab Team Folder/People/BioinfoUndergrads/SCLCproject/4dataset_nonsilent

**Comment by varsh1090** [comment]
Updated input files uploaded to sclc-scripts/data/ in github as well.

**Comment by victorlin** [comment]
Some errors that can't be handled by the current script:

* Lines 2340, 3216, 5861, and 6734 in `4dataset_nonsilent.txt` are empty.
* The p-value (and q-value) for **TP53** in `SigGenes_001_010317.txt` has value 0.

**Comment by varsh1090** [comment]
Data for gene pairs analysis - Dropbox (ZhouLab)/ZhouLab Team Folder/Projects/Oncogenomics/SCLC/Mutsig/HeuristicAnalysis/GenePairs/4datasets_genepairs

**Comment by varsh1090** [comment]
New source files -

1. genenonsilent200.txt to be replaced with 4dataset_nonsilent.txt
2. PercDict.dic and GeneNumDict.dic can be generated from file - 4datasets_GenePerc.txt (Column 1 is gene, column 2 is GeneNum and column 3 is GenePerc)
3. Gene list to be used - 4datasets_MoreThan2

**Comment by varsh1090** [comment]
Repeat analysis for gene lists - SigGenes_001_list.txt and SigGenes_005_list.txt
