### ISSUE TITLE
Comutation plot – adjust dimensions based on font

### ISSUE THREAD

**Issue by victorlin** [zhoulab/sclc-scripts#5]
![sclc_comut_plot_001_4dataset](https://cloud.githubusercontent.com/assets/13424970/21755720/202b9264-d5e6-11e6-9f49-6f6d61919700.jpg)

**Comment by varsh1090** [comment]
Make another figure with only the top 8 genes to make it easier to read.

**Comment by victorlin** [comment]
I have a feeling that this is not possible with `matplotlib`. Closing because we have the option to limit number of genes now, and font size can be adjusted manually if needed.
