### ISSUE TITLE
co-mut plot for p < 0.05 genes

### ISSUE THREAD

**Issue by varsh1090** [zhoulab/sclc-scripts#9]
Command used - 

python genes_001.py --mutsig_genes_file ../data/SigGenes_005.txt --mutation_tsv_file ../data/4dataset_nonsilent.txt -p 0.05 -o ../results/SCLC_comut_plot_005.pdf --sample_id_out ../results/SampleIDs005.txt --num_genes 225

The figure does not seem right, I am not sure what is the issue, could be because the dimensions dont fit 225 genes in the list. Please take a look and let me know how to fix this. Thanks

**Comment by victorlin** [comment]
The plot was not designed to fit `--num_genes 225`. We used it with the top 10 genes in the past. If you want more genes, I could increase the vertical height of the plot, or we would have to discuss how to arrange them visually so the plot is readable.

**Comment by varsh1090** [comment]
Dr. Zhou wants the plot for the 225 genes to be in the supplementary data, even if it is not that readable. If we could observe the patterns of mutations and gene names, that would suffice. Please let me know if you could modify the height of the plot and we can see how it looks.

**Comment by victorlin** [comment]
![sclc_comut_plot_005](https://cloud.githubusercontent.com/assets/13424970/23835465/3c6c1ece-073e-11e7-84bf-6ff326166acc.png)

[SCLC_comut_plot_005.pdf](https://github.com/victor-lin/sclc-scripts/files/836864/SCLC_comut_plot_005.pdf)

**Comment by varsh1090** [comment]
Thanks, could we also have a comut plot for the p<0.01 genes? These are much less in number (--num_genes 56).

**Comment by varsh1090** [comment]
Do we have that plotted already from before? I feel like we did but I cant find it in HPC.

**Comment by victorlin** [comment]
Here is the result with `--num_genes 56`:

![sclc_comut_plot_005](https://cloud.githubusercontent.com/assets/13424970/23839377/f9dac94e-0773-11e7-9a7a-90b8113205d3.png)

[SCLC_comut_plot_005.pdf](https://github.com/victor-lin/sclc-scripts/files/837141/SCLC_comut_plot_005.pdf)

Basically you have to change the `fontsize` in this line:

    ax1.set_yticklabels(genes_list, fontsize=13, va='center', minor=True)

and adjust the dimensions in this line:

    plt.rcParams["figure.figsize"] = [20.0, 5.0]

I've also removed the legend from these renderings for simplicity.

**Comment by varsh1090** [comment]
Great, thanks. This file should be renamed to SCLC_comut_plot_0.01.pdf

**Comment by victorlin** [comment]
Uploaded everything to `/ufrc/zhou/share/projects/bioinformatics/SCLC/sclc-scripts/results/comutation-plot_031217`.

**Comment by varsh1090** [comment]
Thanks, this issue can be closed.
